
INSERT INTO ROLES (NAME) VALUES ("ADMIN"), ("USER"), ("FOTOGRAF");

INSERT INTO DIMENSIUNI_COPERTA (DIMENSIUNI) VALUES
('13x13'),
('15x15'),
('15x20'),
('20x20'),
('20x25'),
('20x30'),
('25x25'),
('30x30'),
('30x40');

INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco01", "eco01.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco02", "eco02.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco03", "eco03.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco04", "eco04.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco05", "eco05.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco06", "eco06.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco07", "eco07.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco08", "eco08.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco09", "eco09.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco10", "eco10.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco11", "eco11.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco12", "eco12.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco13", "eco13.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco14", "eco14.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco15", "eco15.jpg");
INSERT INTO MATERIALE_COPERTA (NUME, IMAGINE) VALUES ("eco16", "eco16.jpg");

INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M01", "M01.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M02", "M02.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M03", "M03.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M04", "M04.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M05", "M05.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M06", "M06.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M07", "M07.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M08", "M08.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M09", "M09.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M10", "M10.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M11", "M11.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M12", "M12.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M13", "M13.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M14", "M14.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M15", "M15.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M16", "M16.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M17", "M17.jpg");
INSERT INTO TIP_COPERTA (NUME, IMAGINE) VALUES ("M18", "M18.jpg");

